# Generated by Django 4.1.4 on 2023-09-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_coupon_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='is_expired',
            new_name='is_available',
        ),
    ]
