# Generated by Django 4.1.4 on 2023-09-26 22:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_rename_is_expired_coupon_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryoffer',
            name='discount_type',
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='categoryoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
