# Generated by Django 4.1.4 on 2023-09-26 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_remove_categoryoffer_discount_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoryoffer',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
    ]
