# Generated by Django 4.1.4 on 2023-09-27 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_categoryoffer_is_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoryoffer',
            name='is_available',
            field=models.BooleanField(),
        ),
    ]
