# Generated by Django 4.2.5 on 2023-10-07 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_remove_recentlysearched_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentlysearched',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
