# Generated by Django 4.2.5 on 2023-10-11 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_review_comment_alter_review_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='product',
        ),
        migrations.RemoveField(
            model_name='review',
            name='user',
        ),
        migrations.DeleteModel(
            name='Referral',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
