# Generated by Django 4.2.5 on 2023-10-03 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0007_wallet_is_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='final_price',
            field=models.FloatField(default=0.0),
        ),
    ]
