# Generated by Django 4.2.5 on 2023-10-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0009_rename_final_price_wallet_final_price_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='extra_paid',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='is_wallet_used',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='wallet_amount_used',
            field=models.FloatField(default=0),
        ),
    ]
