# Generated by Django 4.2.5 on 2023-10-04 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0010_order_extra_paid_order_is_wallet_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='final_price_to_pay',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
