# Generated by Django 4.2.5 on 2023-10-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_productoffer'),
        ('orderapp', '0011_alter_wallet_final_price_to_pay'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.shippingaddress'),
        ),
    ]
