# Generated by Django 4.2.5 on 2023-10-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0012_orderproduct_shipping_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(default='cod', max_length=100),
        ),
    ]
