# Generated by Django 4.2.5 on 2023-10-10 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0013_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='total_with_tax',
            field=models.FloatField(default=0),
        ),
    ]
