# Generated by Django 4.2.5 on 2023-10-11 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderapp', '0015_order_coupon_amt_order_is_coupon_used'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='coupon_amt',
            new_name='coupon_amount',
        ),
    ]
