# Generated by Django 4.1.4 on 2023-09-14 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_cart_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
