# Generated by Django 4.1.4 on 2023-09-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_remove_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='cart_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
