# Generated by Django 4.1.4 on 2023-09-23 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
        ('cartapp', '0010_alter_wishlist_product'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='color',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color'),
        # ),
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='product',
        #     field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='product_variant',
        #     field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        #     preserve_default=False,
        # ),
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='size',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size'),
        # ),
        # migrations.AddField(
        #     model_name='cartitem',
        #     name='user',
        #     field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        # ),
    ]
