# Generated by Django 4.1.4 on 2023-09-27 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryoffer_is_available'),
        ('cartapp', '0013_remove_cartitem_coupon_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
        ),
    ]
