# Generated by Django 4.1.4 on 2023-09-27 08:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryoffer_is_available'),
        ('cartapp', '0015_alter_wishlist_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='productvariant',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='shop.productvariant'),
            preserve_default=False,
        ),
    ]
