# Generated by Django 4.1.4 on 2023-09-27 08:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_categoryoffer_is_available'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cartapp', '0016_wishlist_productvariant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wishlist',
            unique_together={('user', 'product', 'productvariant')},
        ),
    ]
