# Generated by Django 4.2.5 on 2023-10-11 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0017_alter_wishlist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='tax_amount',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='total_with_tax',
            field=models.FloatField(default=0),
        ),
    ]
