# Generated by Django 4.2.5 on 2023-10-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0019_cart_coupon_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_wallet_used',
            field=models.BooleanField(default=False),
        ),
    ]
